### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by inakiabt** [hiroara/TiMessagesTableViewController#1]
First of all, great work :+1: 

I'm trying to compile the module and after run `pod install` and `python build.py`I get these errors:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: -dynamic not specified the following flags are invalid: -ObjC
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods is not an object file (not allowed in a library)

** BUILD FAILED **


The following build commands failed:
    Libtool build/TiMessagesTableViewController.build/Release-iphoneos/TiMessagesTableViewController.build/Objects-normal/armv7/libComArihiroMessagestable.a normal armv7
    Libtool build/TiMessagesTableViewController.build/Release-iphoneos/TiMessagesTableViewController.build/Objects-normal/armv7s/libComArihiroMessagestable.a normal armv7s
    Libtool build/TiMessagesTableViewController.build/Release-iphoneos/TiMessagesTableViewController.build/Objects-normal/arm64/libComArihiroMessagestable.a normal arm64
(3 failures)
xcodebuild failed
```

Am I missing something?
Can you upload a release?
Thanks.

**Comment by mikefogg** [comment]
@hiroara Quick question, been a while since this but I'm still a bit confused as to how this works :)

You mentioned: Run "Pods" project using Release configuration on Xcode and create ./Build/Products/Release-iphoneos/libPods.a

Any chance you can elaborate on that a bit more? I cannot seem to get it to create a libPods.a file at all

**Comment by hiroara** [comment]
@mikefogg OK, please see following screenshots.

First, expand project selectbox from top-left of Xcode and select `Pods` project and `iOS Device`.

<img width="800" alt="2015-10-18 13 27 59" src="https://cloud.githubusercontent.com/assets/1583848/10562553/1707d388-759c-11e5-83d6-89ad5dc2ca5c.png">

Next, open editor of `Run` scheme and select `Release` as Build Configuration. And then run this project.

<img width="1215" alt="2015-10-18 13 29 11" src="https://cloud.githubusercontent.com/assets/1583848/10562557/418d5a24-759c-11e5-9939-98ed78c52fde.png">

After built, `libPods.a` is created under `Build` directory on my environment.

```
$ ls Build/Products/Release-iphoneos/ # maybe `build/~` directory
libPods-JSMessagesViewController.a      libPods-JSQSystemSoundPlayer.a          libPods.a
```

But I'm sorry that I don't ensure that building processes are completed successfully using newer iOS SDK because I don't use anymore this library on my project.
