### ISSUE TITLE
Media Messages?

### ISSUE THREAD

**Issue by khalilsarabey** [hiroara/TiMessagesTableViewController#6]
Hello!
Great job you did here! 
One question though, are you planning to add media messages ?

**Comment by hiroara** [comment]
Hello, thank you for your comment!
First, I haven't planned about media messages yet, but I'm feeling useful enough.
I don't know when I will implement it, but I would like to consider it.
Thank you!

**Comment by kosso** [comment]
+1 please :)

**Comment by yozef** [comment]
+1 too... looks this would replace my current imitation of this effect.

**Comment by korelogic** [comment]
Any update on media messages?

**Comment by hiroara** [comment]
@korelogic Hi, thank you for your interest.

> Any update on media messages?

Yes, but only partially.

I understand that [JSMessagesViewController 4.0](http://cocoadocs.org/docsets/JSMessagesViewController/4.0.0/) has no way to contain media content in messages, but [latest JSQMessagesViewController](https://github.com/jessesquires/JSQMessagesViewController) has it.
Given these facts, TiMessagesTableViewController has no feasibility to implement media messages naturally, because it uses JSMessagesViewController 4.0.

Therefore, I'd planned to implement to contain subview in message bubble easily. But I think that this idea is stopgap. (Actually I tried it, but those codes are little dirty...)
I want to update to JSQMessagesViewController, but I have no time enough to do it now.

The current state is as above.
For now, I've planned to add an implementation to add subview in a little while.

**Comment by hiroara** [comment]
I added subview feature (#10).

This library that run as wrapper have limitation to add features.
Fundamentally, I think that it need newer version library to provide this feature.
For now, I'll close this issue by implementation of subview feature.

If you see some strange behaviors in this library, I'll welcome PR. Thank you.
